use std::fs;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Lockfile {
    pub version: u32,
    #[serde(rename = "package", default)]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: String,
    pub checksum: String,
    #[serde(default)]
    pub dependencies: Vec<String>,
}

impl Lockfile {
    pub fn new() -> Self {
        Self {
            version: 1,
            packages: Vec::new(),
        }
    }

    pub fn from_file(path: &Path) -> Result<Self, String> {
        let content = fs::read_to_string(path)
            .map_err(|e| format!("Could not read Forge.lock at '{}': {}", path.display(), e))?;
        Self::from_str(&content)
    }

    pub fn from_str(content: &str) -> Result<Self, String> {
        toml::from_str(content)
            .map_err(|e| format!("Failed to parse Forge.lock: {}", e))
    }

    pub fn to_toml(&self) -> Result<String, String> {
        let mut out = String::from("# This file is automatically generated by Forge.\n# It is not intended for manual editing.\n\n");
        let toml_body = toml::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize Forge.lock: {}", e))?;
        out.push_str(&toml_body);
        Ok(out)
    }

    pub fn write_file(&self, path: &Path) -> Result<(), String> {
        let content = self.to_toml()?;
        fs::write(path, content)
            .map_err(|e| format!("Could not write Forge.lock to '{}': {}", path.display(), e))
    }

    pub fn find_package(&self, name: &str, version: Option<&str>) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| {
            if p.name != name {
                return false;
            }
            if let Some(v) = version {
                p.version == v
            } else {
                true
            }
        })
    }

    pub fn upsert_package(&mut self, pkg: LockedPackage) {
        if let Some(pos) = self.packages.iter().position(|p| p.name == pkg.name && p.version == pkg.version) {
            self.packages[pos] = pkg;
        } else {
            self.packages.push(pkg);
        }
        self.packages.sort_by(|a, b| (&a.name, &a.version).cmp(&(&b.name, &b.version)));
    }
}

/// Compute deterministic SHA-256 checksum across all `.tg` files in package directory
pub fn compute_package_checksum(dir: &Path) -> Result<String, String> {
    let mut files = Vec::new();
    collect_tg_files(dir, dir, &mut files)?;
    files.sort();

    let mut hasher = Sha256::new();
    for (rel_path, abs_path) in files {
        hasher.update(rel_path.as_bytes());
        hasher.update(&[0u8]); // delimiter
        let content = fs::read(&abs_path)
            .map_err(|e| format!("Failed to read '{}' for checksum: {}", abs_path.display(), e))?;
        hasher.update(&content);
        hasher.update(&[0u8]);
    }

    let result = hasher.finalize();
    Ok(format!("{:x}", result))
}

fn collect_tg_files(base_dir: &Path, current_dir: &Path, list: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    if !current_dir.is_dir() {
        return Ok(());
    }

    let entries = fs::read_dir(current_dir)
        .map_err(|e| format!("Failed to read directory '{}': {}", current_dir.display(), e))?;

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let dir_name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if dir_name != "target" && dir_name != ".git" {
                collect_tg_files(base_dir, &path, list)?;
            }
        } else if path.extension().and_then(|s| s.to_str()) == Some("tg") {
            if let Ok(rel) = path.strip_prefix(base_dir) {
                let rel_str = rel.to_string_lossy().replace('\\', "/");
                list.push((rel_str, path));
            }
        }
    }

    Ok(())
}