use std::process::Command;
use std::time::Duration;
use tempfile::TempDir;

use forge::builder::{build_target, BuildOptions};

#[test]
fn test_milestone3_bootstrap_grand_loop() {
    let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();

    let temp = TempDir::new().unwrap();
    let tgc_exe = temp.path().join("tgc_test.exe");

    let compiler_main = root.join("compiler").join("main.tg");
    assert!(compiler_main.is_file(), "compiler/main.tg must exist at {}", compiler_main.display());

    // Stage 1: Build the self-hosting compiler frontend using Forge
    let opts = BuildOptions {
        release: false,
        emit_llvm: false,
        emit_asm: false,
        custom_out: Some(tgc_exe.clone()),
        target: None,
    };

    let built_exe = build_target(Some(compiler_main.to_str().unwrap()), &opts)
        .expect("Forge must successfully compile compiler/main.tg into tgc");
    assert!(built_exe.is_file(), "tgc executable must be produced");

    // Stage 2: Execute tgc in workspace root to compile examples/bootstrap_sample.tg
    let mut out_res = None;
    for attempt in 0..15 {
        match Command::new(&built_exe).current_dir(&root).output() {
            Ok(out) => {
                out_res = Some(out);
                break;
            }
            Err(e) if e.raw_os_error() == Some(5) => {
                std::thread::sleep(Duration::from_millis(25 * (attempt + 1)));
            }
            Err(e) => panic!("Failed to run binary {}: {}", built_exe.display(), e),
        }
    }
    let tgc_out = out_res.expect("tgc execution must succeed");
    println!("DEBUG TGC: status={:?}, stdout={}, stderr={}", tgc_out.status, String::from_utf8_lossy(&tgc_out.stdout), String::from_utf8_lossy(&tgc_out.stderr));
    assert!(tgc_out.status.success(), "tgc must exit with code 0");
    let tgc_stdout = String::from_utf8_lossy(&tgc_out.stdout);
    assert!(
        tgc_stdout.contains("TGC: Bootstrap Stage 1 compilation completed successfully!"),
        "tgc stdout must indicate successful compilation. Stdout: {}",
        tgc_stdout
    );

    // Stage 3: Verify the compiled bootstrap_sample.exe
    let sample_exe = root.join("examples").join("bootstrap_sample.exe");
    assert!(sample_exe.is_file(), "examples/bootstrap_sample.exe must be generated by tgc");

    let mut sample_res = None;
    for attempt in 0..15 {
        match Command::new(&sample_exe).current_dir(&root).output() {
            Ok(out) => {
                sample_res = Some(out);
                break;
            }
            Err(e) if e.raw_os_error() == Some(5) => {
                std::thread::sleep(Duration::from_millis(25 * (attempt + 1)));
            }
            Err(e) => panic!("Failed to run binary {}: {}", sample_exe.display(), e),
        }
    }
    let sample_out = sample_res.expect("bootstrap_sample.exe execution must succeed");
    assert!(sample_out.status.success(), "bootstrap_sample.exe must exit with code 0");
    let sample_stdout = String::from_utf8_lossy(&sample_out.stdout);

    // Verify arithmetic, recursion, and loops:
    // 1..10 sum = 55
    // 5! = 120
    // add(40, 2) = 42
    assert!(sample_stdout.contains("55"), "Must output sum of 1..10 (55). Stdout: {}", sample_stdout);
    assert!(sample_stdout.contains("120"), "Must output 5! (120). Stdout: {}", sample_stdout);
    assert!(sample_stdout.contains("42"), "Must output add(40, 2) (42). Stdout: {}", sample_stdout);
}
