[package]
name = "forge"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tungsten-syntax = { path = "../tungsten-syntax" }
tungsten-typeck = { path = "../tungsten-typeck" }
tungsten-vm = { path = "../tungsten-vm" }
tungsten-lsp = { path = "../tungsten-lsp" }
tungsten-tir = { path = "../tungsten-tir" }
tungsten-codegen = { path = "../tungsten-codegen" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
sha2 = "0.10"
semver = "1.0"

[dev-dependencies]
tempfile = "3.8"
